default-lease-time 600;
max-lease-time 7200;
authoritative;

# Subnet khusus untuk Docker Isolated Network
subnet 13.13.13.0 netmask 255.255.255.0 {
  range 13.13.13.3 13.13.13.20;
  option routers 13.13.13.1;
  option domain-name-servers 8.8.8.8, 1.1.1.1;
}
