# Port DNS dimatikan karena kita cuma butuh DHCP
port=0

# Log lengkap untuk kebutuhan Laporan Praktikum
log-dhcp
log-queries

# Interface internal container
interface=eth0

# Rentang IP yang dibagikan dan Subnet Mask
dhcp-range=13.13.13.2,13.13.13.20,255.255.255.0,12h

# Gateway (IP WSL kamu)
dhcp-option=3,13.13.13.1

# DNS Server untuk client
dhcp-option=6,8.8.8.8,1.1.1.1
