events { }

http {
    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;

        # Mengizinkan browser menampilkan list folder jika buka root /
        autoindex on;

        # Set file default jika membuka /siswa/ atau /guru/
        index latihanftpdocker.txt;

        # Akses untuk SISWA (Langsung tanpa login)
        location /siswa/ {
            try_files $uri $uri/ =404;
        }

        # Akses untuk GURU (Ada notifikasi login)
        location /guru/ {
            auth_basic "Akses Terbatas - Area Guru";
            auth_basic_user_file /etc/nginx/.htpasswd;

            add_header Cache-Control "no-cache, no-store, must-revalidate";
            add_header Pragma "no-cache";
            add_header Expires "0";

            try_files $uri $uri/ =404;
        }
    }
}
