services:
  samba:
    image: dperson/samba
    container_name: samba-server

    ports:
      - "445:445"
      - "139:139"
      - "137:137/udp"
      - "138:138/udp"

    volumes:
      - ./data:/data

    command: >
      -u "guru;123"
      -s "siswa;/data/siswa;yes;no;yes"
      -s "guru;/data/guru;yes;no;no;guru"

    restart: unless-stopped
