# Menggunakan NTP pool Indonesia
pool 0.id.pool.ntp.org iburst
pool 1.id.pool.ntp.org iburst
pool 2.id.pool.ntp.org iburst
pool 3.id.pool.ntp.org iburst

# Mengizinkan akses dari semua IP (subnet Docker/Lokal)
allow 0.0.0.0/0
allow ::/0

# File lacak penyimpangan waktu (drift)
driftfile /var/lib/chrony/chrony.drift

# Direktori log
logdir /var/log/chrony

# Lakukan penyesuaian instan (step) jika selisih > 1 detik di 3 pemeriksaan awal
makestep 1.0 3

# Melayani query NTP meskipun belum tersinkronisasi penuh dengan upstream
local stratum 10
