# Matikan fungsi DNS
port=0

# Aktifkan log DHCP untuk bukti laporan
log-dhcp

# Rentang IP DHCP yang akan diberikan ke Windows (sesuaikan IP dengan subnet WSL kamu)
# Format: dhcp-range=<IP_Awal>,<IP_Akhir>,<Netmask>,<LeaseTime>
dhcp-range=172.29.29.100,172.29.29.150,255.255.240.0,12h

# Set Option 3 (Router/Gateway) ke IP WSL kamu
dhcp-option=3,172.29.29.113

# Set Option 6 (DNS Server)
dhcp-option=6,8.8.8.8
